// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpotRlhJN_O4XyVsvEonR-A5OgjFe_DTY',
    appId: '1:639823685068:web:49ae527b5da218629ee969',
    messagingSenderId: '639823685068',
    projectId: 'reelant-53374',
    authDomain: 'reelant-53374.firebaseapp.com',
    storageBucket: 'reelant-53374.appspot.com',
    measurementId: 'G-D8N2P2N3KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcrFXMmdTDeD0mSCrbEFofNAMSXDOcZaY',
    appId: '1:639823685068:android:b7b94577701e91b39ee969',
    messagingSenderId: '639823685068',
    projectId: 'reelant-53374',
    storageBucket: 'reelant-53374.appspot.com',
  );
}
